<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="19088" started-at="2018-12-31T21:08:53Z" finished-at="2018-12-31T21:09:12Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="19088" started-at="2018-12-31T21:08:53Z" finished-at="2018-12-31T21:09:12Z">
      <class name="com.Catalog.qa.testcases.LoginTestcase">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.Catalog.qa.testcases.LoginTestcase@3fd7a715]" name="setUp" is-config="true" duration-ms="6015" started-at="2018-12-31T21:08:54Z" finished-at="2018-12-31T21:09:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testcase01(java.lang.String, java.lang.String)[pri:1, instance:com.Catalog.qa.testcases.LoginTestcase@3fd7a715]" name="testcase01" duration-ms="1124" started-at="2018-12-31T21:09:00Z" data-provider="getcatalogdata" finished-at="2018-12-31T21:09:01Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ecalix]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[test123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Welcome, Please Sign In] but found [Welcome to iBusiness]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Welcome, Please Sign In] but found [Welcome to iBusiness]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.Catalog.qa.pages.Homepage.verifyHeader(Homepage.java:51)
at com.Catalog.qa.testcases.LoginTestcase.testcase01(LoginTestcase.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase01 -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.Catalog.qa.testcases.LoginTestcase@3fd7a715]" name="setUp" is-config="true" duration-ms="3976" started-at="2018-12-31T21:09:01Z" finished-at="2018-12-31T21:09:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testcase01(java.lang.String, java.lang.String)[pri:1, instance:com.Catalog.qa.testcases.LoginTestcase@3fd7a715]" name="testcase01" duration-ms="1253" started-at="2018-12-31T21:09:05Z" data-provider="getcatalogdata" finished-at="2018-12-31T21:09:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ecalix@]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[test123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Welcome, Please Sign In] but found [Welcome to iBusiness]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Welcome, Please Sign In] but found [Welcome to iBusiness]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.Catalog.qa.pages.Homepage.verifyHeader(Homepage.java:51)
at com.Catalog.qa.testcases.LoginTestcase.testcase01(LoginTestcase.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase01 -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.Catalog.qa.testcases.LoginTestcase@3fd7a715]" name="setUp" is-config="true" duration-ms="4365" started-at="2018-12-31T21:09:06Z" finished-at="2018-12-31T21:09:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testcase01(java.lang.String, java.lang.String)[pri:1, instance:com.Catalog.qa.testcases.LoginTestcase@3fd7a715]" name="testcase01" duration-ms="1651" started-at="2018-12-31T21:09:10Z" data-provider="getcatalogdata" finished-at="2018-12-31T21:09:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ecalix@test.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[test123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase01 -->
      </class> <!-- com.Catalog.qa.testcases.LoginTestcase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
